# .pre-commit-config.yaml
default_stages: [commit, push]
default_language_version:
  python: python3.11

repos:
  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  # Linting (rules configured in pyproject.toml)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        # Autofix and fail if changes were required (so you re-run hooks)
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        # Make sure pre-commit's isolated env has what mypy needs
        additional_dependencies:
          - sqlalchemy>=2.0
          - pydantic>=2.7
          - typing-extensions>=4.11
          - types-requests>=2.32.0.20240914
        # Limit to your code dirs; adjust as needed
        files: "^(app|api|scripts|alembic)/"
