from __future__ import annotations

import logging
import queue
import smtplib
import ssl
import threading
import time
from email.message import EmailMessage
from typing import Any

from app.config import settings

logger = logging.getLogger("glycofy.alert_delivery")
_QUEUE: queue.Queue[dict[str, Any]] = queue.Queue(maxsize=100)
_LOCK = threading.Lock()
_WORKER_STARTED = False
_LAST_SENT: dict[str, float] = {}


def email_delivery_configured() -> bool:
    return bool(
        settings.SECURITY_ALERT_EMAIL_ENABLED
        and settings.SECURITY_ALERT_EMAIL_TO
        and settings.SMTP_HOST
        and settings.SMTP_FROM_EMAIL
    )


def build_alert_message(event: dict[str, Any]) -> EmailMessage:
    message = EmailMessage()
    message["To"] = settings.SECURITY_ALERT_EMAIL_TO
    message["From"] = settings.SMTP_FROM_EMAIL or "alerts@glycofy.ai"
    message["Subject"] = f"[Glycofy security] {event['event_type']}: {event['outcome']}"
    message.set_content(
        "A security alert was generated by Glycofy.\n\n"
        f"Event: {event['event_type']}\n"
        f"Outcome: {event['outcome']}\n"
        f"Request ID: {event.get('request_id') or 'unavailable'}\n"
        f"User ID: {event.get('user_id') if event.get('user_id') is not None else 'unavailable'}\n\n"
        "Review the structured application logs and security_audit_events table for context. "
        "Sensitive credentials and personal data are intentionally omitted from this email.\n"
    )
    return message


def _deliver(event: dict[str, Any]) -> None:
    message = build_alert_message(event)
    if settings.SMTP_USE_TLS:
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=15) as smtp:
            smtp.starttls(context=ssl.create_default_context())
            if settings.SMTP_USERNAME and settings.SMTP_PASSWORD:
                smtp.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            smtp.send_message(message)
    else:
        with smtplib.SMTP_SSL(
            settings.SMTP_HOST,
            settings.SMTP_PORT,
            timeout=15,
            context=ssl.create_default_context(),
        ) as smtp:
            if settings.SMTP_USERNAME and settings.SMTP_PASSWORD:
                smtp.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            smtp.send_message(message)


def _worker() -> None:
    while True:
        event = _QUEUE.get()
        try:
            _deliver(event)
            logger.info(
                "security_alert_email_sent",
                extra={"event_type": event["event_type"], "request_id": event.get("request_id")},
            )
        except Exception:
            logger.exception(
                "security_alert_email_failed",
                extra={"event_type": event["event_type"], "request_id": event.get("request_id")},
            )
        finally:
            _QUEUE.task_done()


def _ensure_worker() -> None:
    global _WORKER_STARTED
    with _LOCK:
        if _WORKER_STARTED:
            return
        threading.Thread(target=_worker, name="glycofy-alert-email", daemon=True).start()
        _WORKER_STARTED = True


def queue_security_alert(event: dict[str, Any]) -> bool:
    if not email_delivery_configured():
        return False

    dedupe_key = f"{event['event_type']}:{event['outcome']}"
    now = time.monotonic()
    with _LOCK:
        last_sent = _LAST_SENT.get(dedupe_key, 0.0)
        if now - last_sent < settings.SECURITY_ALERT_EMAIL_COOLDOWN_SECONDS:
            return False
        _LAST_SENT[dedupe_key] = now

    _ensure_worker()
    try:
        _QUEUE.put_nowait(event)
        return True
    except queue.Full:
        logger.error("security_alert_email_queue_full", extra={"event_type": event["event_type"]})
        return False
